---
- name: SUSE Hardening Ayarlari
  hosts: suse_hosts
  become: yes

  vars:
    session_timeout_seconds: 900
    max_password_age: 90
    min_password_age: 7
    max_password_attempts: 5
    password_lockout_time: 900

    # pwquality ayarları
    pwq_minlen: 12
    pwq_dcredit: 1
    pwq_ucredit: 1
    pwq_ocredit: 1
    pwq_lcredit: 1

  tasks:

    # --- 2. Çekirdek (Kernel/Sysctl) Güvenlik Ayarları ---

    - name: 2.1. Core Dump'lari Devre Disi Birak
      copy:
        content: "* hard core 0\n"
        dest: /etc/security/limits.d/core_security.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - limits
        - core_dump
      diff: yes
      register: core_dump_result

    - debug:
        var: core_dump_result

    - name: 2.2. Sysctl Ayarlari (net.ipv4 Hardening)
      sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        state: present
        reload: yes
      loop:
        - { key: 'net.ipv4.ip_forward', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
        - { key: 'net.ipv4.tcp_syncookies', value: '1' }
        - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
        - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
        - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
      tags:
        - sysctl
        - network
      diff: yes
      register: sysctl_result

    - debug:
        var: sysctl_result

    - name: 2.3. USB Otomatik Yüklemeyi Devre Disi Birak
      lineinfile:
        path: /etc/modprobe.d/usb_blacklist.conf
        line: 'install usb-storage /bin/true'
        create: yes
        state: present
      tags:
        - modprobe
        - usb
      diff: yes
      register: usb_blacklist_result

    - debug:
        var: usb_blacklist_result

    # --- 3. Kullanıcı ve Parola Politikaları ---
    # Not: 3.1 ve 3.4 görevleri kilitlenme riskini azaltmak için en sona taşınmıştır.

    - name: 3.2. Parola Politikalarini Guclendir (/etc/login.defs)
      lineinfile:
        path: /etc/login.defs
        regexp: '^{{ item.regex }}'
        line: '{{ item.line }}'
        state: present
      loop:
        - { regex: '^PASS_MAX_DAYS', line: 'PASS_MAX_DAYS\t{{ max_password_age }}' }
        - { regex: '^PASS_MIN_DAYS', line: 'PASS_MIN_DAYS\t{{ min_password_age }}' }
        - { regex: '^PASS_WARN_AGE', line: 'PASS_WARN_AGE\t7' }
      tags:
        - password_policy
        - login_defs
      diff: yes
      register: login_defs_result

    - debug:
        var: login_defs_result

    - name: 3.3. Parola Karmasiklik Gereksinimi (/etc/security/pwquality.conf)
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^{{ item.regex }}'
        line: '{{ item.line }}'
        state: present
      loop:
        - { regex: '^minlen', line: 'minlen = {{ pwq_minlen }}' }
        - { regex: '^dcredit', line: 'dcredit = {{ pwq_dcredit }}' }
        - { regex: '^ucredit', line: 'ucredit = {{ pwq_ucredit }}' }
        - { regex: '^ocredit', line: 'ocredit = {{ pwq_ocredit }}' }
        - { regex: '^lcredit', line: 'lcredit = {{ pwq_lcredit }}' }
      tags:
        - pam
        - password_complexity
        - pwquality
      diff: yes
      register: pwquality_result

    - debug:
        var: pwquality_result

    # --- 4. Dosya Sistemi İzinleri ve Kontrolleri ---

    - name: 4.1. Kullanici Ana Dizin ve Shell Dosyalarinin Izinlerini Ayarla
      file:
        path: '{{ item }}'
        mode: '0600'
        owner: root
        group: root
      loop:
        - /root/.bashrc
        - /root/.profile
        - /root/.bash_history
        - /root/.bash_logout
      tags:
        - file_permissions
      diff: yes
      register: file_permissions_result

    - debug:
        var: file_permissions_result

    - name: 4.2. Hassas Sistem Dosyalarinin Izinlerini Ayarla
      file:
        path: '{{ item.path }}'
        mode: '{{ item.mode }}'
      loop:
        - { path: /etc/passwd, mode: '0644' }
        - { path: /etc/shadow, mode: '0000' }
        - { path: /etc/group, mode: '0644' }
        - { path: /etc/gshadow, mode: '0000' }
      tags:
        - file_permissions
        - sensitive_files
      diff: yes
      register: sensitive_files_result

    - debug:
        var: sensitive_files_result

    # --- 5. Diğer Güvenlik Ayarları ---

    - name: 5.1. ctrl-alt-del Islemini Devre Disi Birak
      file:
        path: /etc/systemd/system/ctrl-alt-del.target
        state: absent
      tags:
        - systemd
        - ctrl_alt_del
      diff: yes
      register: ctrl_alt_del_result

    - debug:
        var: ctrl_alt_del_result

    - name: 5.2. /etc/issue ve /etc/issue.net Dosyalarini Guvenlik Bilgileriyle Guncelle
      copy:
        content: |
          Authorized uses only. All activity is logged and monitored. Unauthorized access is prohibited.
        dest: '{{ item }}'
        owner: root
        group: root
        mode: '0644'
      loop:
        - /etc/issue
        - /etc/issue.net
      tags:
        - banner
      diff: yes
      register: banner_result

    - debug:
        var: banner_result

    - name: 5.3. AppArmor'u Etkinlestir ve Profilleri Zorunlu Moda Al
      command: 'aa-enforce /etc/apparmor.d/*'
      args:
        warn: no
      ignore_errors: yes
      changed_when: true
      tags:
        - mac
        - apparmor
      register: apparmor_result

    - debug:
        var: apparmor_result

    # 🛑 EN SON GÜVENLİK ADIMLARI (Bağlantı Kesme Riski Olanlar)

    - name: Z.98. Kullanici Oturum Zaman Asimi Ayari (SONA TAŞINDI)
      block:
        - name: Timeout.sh dosyasi olustur
          copy:
            content: |
              # /etc/profile.d/timeout.sh
              # Kullanici oturum zaman asimi ayari
              TMOUT={{ session_timeout_seconds }}
              readonly TMOUT
              export TMOUT
            dest: /etc/profile.d/timeout.sh
            owner: root
            group: root
            mode: '0644'
          tags:
            - timeout
          diff: yes
          register: timeout_final_result

    - debug:
        var: timeout_final_result

    - name: Z.99. Basarisiz Giris Denemesi Limiti ve Kilitlenme Ayari (SON GÖREV)
      blockinfile:
        path: /etc/pam.d/common-auth-pc
        block: |
          auth    required    pam_faillock.so preauth silent audit deny={{ max_password_attempts }} unlock_time={{ password_lockout_time }}
          auth    [default=die]    pam_faillock.so authfail audit deny={{ max_password_attempts }} unlock_time={{ password_lockout_time }}
          auth    sufficient    pam_faillock.so authsucc audit
        marker: "# {mark} ANSIBLE MANAGED BLOCK - PAM FAILLOCK"
      tags:
        - pam
        - lockout
      diff: yes
      register: faillock_result

    - debug:
        var: faillock_result
