---
- name: SUSE Hardening + Audit + Logging + Performance
  hosts: suse_hosts
  become: yes

  vars:
    session_timeout_seconds: 900
    max_password_age: 90
    min_password_age: 7
    max_password_attempts: 5
    password_lockout_time: 900

    # pwquality ayarlar覺
    pwq_minlen: 12
    pwq_dcredit: 1
    pwq_ucredit: 1
    pwq_ocredit: 1
    pwq_lcredit: 1

    # HISTIGNORE
    histignore_block: |
      export HISTIGNORE="SUSEConnect *:subscription-manager *:rhn-register *"
      export HISTIGNORE="subscription-manager *:rhn-register *"
      export HISTIGNORE="SUSEConnect *"
      source /etc/profile

    # Performance parametreleri
    nofile_limit: 65535
    nproc_limit: 65535

  tasks:

    # --- 1. HISTIGNORE ---
    - name: Backup /etc/profile before HISTIGNORE changes
      copy:
        src: /etc/profile
        dest: /etc/profile.bak
        owner: root
        group: root
        mode: '0644'
      tags:
        - histignore

    - name: Set HISTIGNORE block in /etc/profile
      blockinfile:
        path: /etc/profile
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HISTIGNORE"
        block: "{{ histignore_block }}"
      tags:
        - histignore

    # --- 2. Kernel/Sysctl & USB ---
    - name: Sysctl hardening
      sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        state: present
        reload: yes
      loop:
        - { key: 'net.ipv4.ip_forward', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
        - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
        - { key: 'net.ipv4.tcp_syncookies', value: '1' }
        - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
        - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
        - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
      tags:
        - sysctl
        - network

    - name: Disable USB auto load
      lineinfile:
        path: /etc/modprobe.d/usb_blacklist.conf
        line: 'install usb-storage /bin/true'
        create: yes
        state: present
      tags:
        - modprobe
        - usb

    # --- 3. Kullan覺c覺 ve parola politikalar覺 ---
    - name: Set password policies in /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - { regex: '^PASS_MAX_DAYS', line: 'PASS_MAX_DAYS\t{{ max_password_age }}' }
        - { regex: '^PASS_MIN_DAYS', line: 'PASS_MIN_DAYS\t{{ min_password_age }}' }
        - { regex: '^PASS_WARN_AGE', line: 'PASS_WARN_AGE\t7' }
      tags:
        - password_policy

    - name: Set pwquality requirements
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^{{ item.regex }}'
        line: '{{ item.line }}'
      loop:
        - { regex: '^minlen', line: 'minlen = {{ pwq_minlen }}' }
        - { regex: '^dcredit', line: 'dcredit = {{ pwq_dcredit }}' }
        - { regex: '^ucredit', line: 'ucredit = {{ pwq_ucredit }}' }
        - { regex: '^ocredit', line: 'ocredit = {{ pwq_ocredit }}' }
        - { regex: '^lcredit', line: 'lcredit = {{ pwq_lcredit }}' }
      tags:
        - pwquality

    - name: Timeout (session inactivity)
      copy:
        content: |
          # /etc/profile.d/timeout.sh
          TMOUT={{ session_timeout_seconds }}
          readonly TMOUT
          export TMOUT
        dest: /etc/profile.d/timeout.sh
        owner: root
        group: root
        mode: '0644'
      tags:
        - timeout

    # --- 4. Performance limits ---
    - name: Set /etc/security/limits.conf for nofile/nproc
      blockinfile:
        path: /etc/security/limits.conf
        block: |
          * soft nofile {{ nofile_limit }}
          * hard nofile {{ nofile_limit }}
          * soft nproc {{ nproc_limit }}
          * hard nproc {{ nproc_limit }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - PERFORMANCE"
      tags:
        - performance

    - name: Set ulimit
      shell: "ulimit -n {{ nofile_limit }}"
      tags:
        - performance

    # --- 5. Journald persistent log ---
    - name: Make journald persistent
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?Storage='
        line: 'Storage=persistent'
      notify: Restart journald
      tags:
        - journald

    # --- 6. Auditd ---
    - name: Ensure auditd is running and enabled
      systemd:
        name: auditd
        state: started
        enabled: yes
      tags:
        - auditd

    # --- 7. Rsyslog ---
    - name: Configure /etc/rsyslog.d/50-default.conf
      copy:
        dest: /etc/rsyslog.d/50-default.conf
        content: |
          cron.*          /var/log/cron.log
          local1.*        /var/log/sudo.log
          auth.*          /var/log/auth.log
          authpriv.*      /var/log/secure
          *.*;auth,authpriv.none  -/var/log/syslog
      notify: Restart rsyslog
      tags:
        - rsyslog

    - name: Add sudo logging defaults
      lineinfile:
        path: /etc/sudoers
        line: 'Defaults log_host, log_year, logfile="/var/log/sudo.log"'
        validate: 'visudo -cf %s'
      tags:
        - sudo_logging

  handlers:
    - name: Restart journald
      systemd:
        name: systemd-journald
        state: restarted

    - name: Restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
